language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/088d6d0266532abc60ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
